### ISSUE TITLE
Bug: redundant jenkins jobs in jenkins view

### ISSUE THREAD

**Issue by bobby-chiu** [AnyStatus/Support#60] opened 2017-12-14 09:00 UTC
this happens on AnyStatus extension 1.4.101 under vs2017 ver.15.5.1

**Comment by bobby-chiu** [comment] 2017-12-14 09:12
To be exact, i found any operation can trigger this problem, all jobs will be copied once and displayed in anystatus explorer

**Comment by AlonAm** [comment] 2017-12-14 20:10
Ill try to reproduce the bug and fix it asap
Thanks for reporting

**Comment by AlonAm** [comment] 2017-12-21 11:59
i was unable to reproduce the bug. can you please describe what happens when the bug occurs? when you click Refresh, the whole Jenkins View duplicates?

**Comment by AlonAm** [comment] 2017-12-21 23:32
I am now able to reproduce the bug.
ill try to release a fix asap
thanks for reporting!

**Comment by AlonAm** [comment] 2018-03-06 07:41
released in 1.6.4

**Closed by AlonAm** 2018-03-06 07:41 UTC
Labels: bug, critical, help wanted
